// Custom Macros — CardMirror Plugin
// Generated by Custom Macros Editor. Do not edit by hand.
// To update, use "Build Plugin" in the editor.

(function () {
  'use strict';

  // ---- EMBEDDED MACROS (generated by editor) ----
  // __MACROS_START__
  var MACROS = [
  {
    "name": "HSTag",
    "steps": [
      { "type": "insert-text", "content": "accessed " },
      { "type": "insert-date", "format": "m.dd.yy" },
      { "type": "insert-text", "content": " // " },
      { "type": "cardmirror", "label": "Bold" },
      { "type": "cardmirror", "label": "Italic" },
      { "type": "insert-text", "content": "mosuQ" },
      { "type": "cardmirror", "label": "Bold" },
      { "type": "cardmirror", "label": "Italic" },
      { "type": "insert-text", "content": "]" }
    ]
  }
];
  // __MACROS_END__

  // ---- Date formatting ----

  var MONTH_NAMES = [
    'January','February','March','April','May','June',
    'July','August','September','October','November','December',
  ];
  var MONTH_ABBR = [
    'Jan','Feb','Mar','Apr','May','Jun',
    'Jul','Aug','Sep','Oct','Nov','Dec',
  ];

  var DATE_TOKENS = [
    { p: 'MONTH', fn: function(d) { return MONTH_NAMES[d.getMonth()].toUpperCase(); } },
    { p: 'Month', fn: function(d) { return MONTH_NAMES[d.getMonth()]; } },
    { p: 'month', fn: function(d) { return MONTH_NAMES[d.getMonth()].toLowerCase(); } },
    { p: 'MON',   fn: function(d) { return MONTH_ABBR[d.getMonth()].toUpperCase(); } },
    { p: 'Mon',   fn: function(d) { return MONTH_ABBR[d.getMonth()]; } },
    { p: 'mon',   fn: function(d) { return MONTH_ABBR[d.getMonth()].toLowerCase(); } },
    { p: 'yyyy',  fn: function(d) { return String(d.getFullYear()); } },
    { p: 'yy',    fn: function(d) { return String(d.getFullYear()).slice(-2); } },
    { p: 'mm',    fn: function(d) { return String(d.getMonth() + 1).padStart(2, '0'); } },
    { p: 'dd',    fn: function(d) { return String(d.getDate()).padStart(2, '0'); } },
    { p: 'm',     fn: function(d) { return String(d.getMonth() + 1); } },
    { p: 'd',     fn: function(d) { return String(d.getDate()); } },
  ];

  function formatDate(fmt, date) {
    var result = '';
    var i = 0;
    while (i < fmt.length) {
      var matched = false;
      for (var t = 0; t < DATE_TOKENS.length; t++) {
        var tok = DATE_TOKENS[t];
        if (fmt.substr(i, tok.p.length) === tok.p) {
          result += tok.fn(date);
          i += tok.p.length;
          matched = true;
          break;
        }
      }
      if (!matched) {
        result += fmt[i];
        i++;
      }
    }
    return result;
  }

  // ---- Label-to-keybind map ----

  var LABEL_KEYBIND_MAP = {
    'new document': 'Mod-n',
    'open file': 'Mod-o',
    'save': 'Mod-s',
    'save as…': 'Mod-Shift-s',
    'save send doc': 'Mod-Alt-s',
    'save marked cards': 'Mod-Alt-m',
    'send to speech (at cursor)': '`',
    'send to speech (at end)': 'Alt-`',
    'send to dropzone': 'Mod-`',
    'insert received card (at cursor)': 'Mod-p',
    'insert received card (at end)': 'Mod-Alt-p',
    'apply pocket style': 'F4',
    'apply hat style': 'F5',
    'apply block style': 'F6',
    'apply tag style': 'F7',
    'apply analytic style': 'Mod-F7',
    'apply undertag style': 'Mod-F8',
    'number: toggle number role': 'Mod-Alt-1',
    'number: toggle substructure role': 'Mod-Alt-2',
    'number: toggle start-over-here': 'Mod-Alt-3',
    'apply cite style': 'F8',
    'toggle underline': 'F9',
    'underline (toggle while typing)': 'Mod-u',
    'apply emphasis style': 'F10',
    'emphasize acronym': 'Alt-F10',
    'toggle highlight': 'F11',
    'highlight acronym': 'Alt-F11',
    'toggle background color': 'Mod-F11',
    'bold': 'Mod-b',
    'italic': 'Mod-i',
    'superscript': 'Mod-Shift-=',
    'subscript': 'Mod-=',
    'condense': 'F3',
    'condense without paragraph integrity': 'Alt-F3',
    'condense without paragraph integrity (with pilcrows)': 'Mod-Alt-F3',
    'uncondense': 'Mod-Alt-Shift-F3',
    'toggle case': 'Shift-F3',
    'paste plain text': 'F2',
    'clear': 'F12',
    'shrink card text': 'Mod-8',
    'smart shrink (deeper for unmarked paragraphs)': 'Mod-Alt-8',
    'restore card text size': 'Mod-Shift-8',
    'copy previous cite': 'Alt-F8',
    'select current heading': 'Alt-a',
    'move container up': 'Mod-Alt-ArrowUp',
    'move container down': 'Mod-Alt-ArrowDown',
    'reading-position marker (toggle)': 'Mod-Shift-d',
    'find': 'Mod-f',
    'find and replace': 'Mod-h',
    'find without category grouping': 'Alt-f',
    'search everything': 'Mod-Shift-Space',
    'minimize window': 'Mod-m',
    'zoom in': 'Mod-=',
    'zoom out': 'Mod--',
    'chrome scale up': 'Mod-Alt-=',
    'chrome scale down': 'Mod-Alt--',
    'reset chrome scale to 100%': 'Mod-Alt-0',
    'add note to selection': 'Mod-Shift-n',
    'focus slot 1': 'Mod-1',
    'focus slot 2': 'Mod-2',
    'focus slot 3': 'Mod-3',
    'send doc to slot 1': 'Mod-Shift-1',
    'send doc to slot 2': 'Mod-Shift-2',
    'send doc to slot 3': 'Mod-Shift-3',
    'toggle slot expand / restore': 'Mod-Shift-f',
    'close doc or window': 'Mod-w',
    'ask ai about selection': 'Mod-Shift-q',
    'format cite from selection (ai)': 'Mod-Shift-x',
    'translate selection to clipboard (ai)': 'Mod-Shift-t',
    'repair ocr/pdf text (ai)': 'Mod-Shift-r',
    'repair formatting (ai)': 'Mod-Alt-r',
    'toggle voice control': 'Mod-Shift-V',
    'cut card with ai…': 'Mod-Alt-c',
  };

  // ---- Keybind parser ----

  function parseKeybind(keybindStr) {
    var parts = keybindStr.split('-');
    var key = parts[parts.length - 1];
    var ctrl = false, meta = false, shift = false, alt = false;
    var isMac = typeof navigator !== 'undefined' && /Mac/.test(navigator.platform);

    for (var i = 0; i < parts.length - 1; i++) {
      var mod = parts[i];
      if (mod === 'Mod') {
        if (isMac) meta = true; else ctrl = true;
      } else if (mod === 'Shift') {
        shift = true;
      } else if (mod === 'Alt') {
        alt = true;
      } else if (mod === 'Control') {
        ctrl = true;
      } else if (mod === 'Meta') {
        meta = true;
      }
    }

    return { key: key, ctrlKey: ctrl, metaKey: meta, shiftKey: shift, altKey: alt };
  }

  // ---- Execution engine ----

  function findEditor() {
    return document.querySelector('.ProseMirror[contenteditable="true"]');
  }

  function insertText(text) {
    var editor = findEditor();
    if (!editor) throw new Error('No active editor found');
    editor.focus();
    var ok = document.execCommand('insertText', false, text);
    if (!ok) {
      var event = new InputEvent('beforeinput', {
        inputType: 'insertText',
        data: text,
        bubbles: true,
        cancelable: true,
      });
      editor.dispatchEvent(event);
    }
  }

  function executeCommand(label) {
    var keybind = LABEL_KEYBIND_MAP[label.toLowerCase()];
    if (!keybind) {
      throw new Error('"' + label + '" has no keybinding. Assign one in CardMirror Settings → Keybindings.');
    }

    var editor = findEditor();
    if (!editor) throw new Error('No active editor found');
    editor.focus();

    var parsed = parseKeybind(keybind);
    var event = new KeyboardEvent('keydown', {
      key: parsed.key,
      ctrlKey: parsed.ctrlKey,
      metaKey: parsed.metaKey,
      shiftKey: parsed.shiftKey,
      altKey: parsed.altKey,
      bubbles: true,
      cancelable: true,
    });
    editor.dispatchEvent(event);
  }

  function evaluateExpression(expr, scope, api) {
    if (expr.type === 'string') return expr.value;
    if (expr.type === 'number') return expr.value;
    if (expr.type === 'variable') {
      return scope.hasOwnProperty(expr.name) ? scope[expr.name] : '';
    }
    if (expr.type === 'binary') {
      var left = Number(evaluateExpression(expr.left, scope, api)) || 0;
      var right = Number(evaluateExpression(expr.right, scope, api)) || 0;
      if (expr.operator === '+') return left + right;
      if (expr.operator === '-') return left - right;
      return 0;
    }
    if (expr.type === 'count') {
      if (!api._countWarned) {
        api.showToast('Document queries require CardMirror API v2');
        api._countWarned = true;
      }
      return 0;
    }
    return '';
  }

  function evaluateAtomicCondition(atom, scope, api) {
    if (atom.type === 'compare') {
      var varVal = scope.hasOwnProperty(atom.variable) ? scope[atom.variable] : '';
      var cmpVal = atom.value.type === 'string' ? atom.value.value : atom.value.value;
      if (atom.operator === '=') return String(varVal) === String(cmpVal);
      if (atom.operator === '>') return Number(varVal) > Number(cmpVal);
      if (atom.operator === '<') return Number(varVal) < Number(cmpVal);
      return false;
    }
    if (atom.type === 'contains') {
      if (!api._queryWarned) {
        api.showToast('Document queries require CardMirror API v2');
        api._queryWarned = true;
      }
      return false;
    }
    return false;
  }

  function evaluateCondition(condition, scope, api) {
    for (var g = 0; g < condition.length; g++) {
      var group = condition[g];
      var groupResult = true;
      for (var a = 0; a < group.length; a++) {
        if (!evaluateAtomicCondition(group[a], scope, api)) {
          groupResult = false;
          break;
        }
      }
      if (groupResult) return true;
    }
    return false;
  }

  function executeMacro(macro, api) {
    var steps = macro.steps;
    var idx = 0;
    var scope = {};
    var blockStack = [];
    var MAX_ITERATIONS = 10000;

    function isSkipping() {
      for (var i = 0; i < blockStack.length; i++) {
        if (blockStack[i].skipping) return true;
      }
      return false;
    }

    function runNext() {
      while (idx < steps.length) {
        var step = steps[idx];
        idx++;

        if (step.type === 'comment') continue;

        // ---- Control flow: always processed ----

        if (step.type === 'if') {
          if (isSkipping()) {
            blockStack.push({ kind: 'if', branchTaken: true, skipping: true });
          } else {
            var ifResult = evaluateCondition(step.condition, scope, api);
            blockStack.push({ kind: 'if', branchTaken: ifResult, skipping: !ifResult });
          }
          continue;
        }
        if (step.type === 'elif') {
          if (blockStack.length > 0 && blockStack[blockStack.length - 1].kind === 'if') {
            var top = blockStack[blockStack.length - 1];
            if (top.branchTaken) {
              top.skipping = true;
            } else {
              var elifResult = evaluateCondition(step.condition, scope, api);
              top.branchTaken = elifResult;
              top.skipping = !elifResult;
            }
          }
          continue;
        }
        if (step.type === 'else') {
          if (blockStack.length > 0 && blockStack[blockStack.length - 1].kind === 'if') {
            var top = blockStack[blockStack.length - 1];
            top.skipping = top.branchTaken;
            top.branchTaken = true;
          }
          continue;
        }

        if (step.type === 'repeat') {
          if (isSkipping()) {
            blockStack.push({ kind: 'repeat', skipping: true });
          } else {
            var countVal = Number(evaluateExpression(step.count, scope, api)) || 0;
            if (countVal <= 0) {
              blockStack.push({ kind: 'repeat', skipping: true });
            } else {
              blockStack.push({ kind: 'repeat', remaining: countVal, startIdx: idx, iterations: 0, skipping: false });
            }
          }
          continue;
        }
        if (step.type === 'while') {
          if (isSkipping()) {
            blockStack.push({ kind: 'while', skipping: true });
          } else {
            var whileResult = evaluateCondition(step.condition, scope, api);
            if (!whileResult) {
              blockStack.push({ kind: 'while', skipping: true });
            } else {
              blockStack.push({ kind: 'while', condition: step.condition, startIdx: idx, iterations: 0, skipping: false });
            }
          }
          continue;
        }

        if (step.type === 'end') {
          if (blockStack.length > 0) {
            var top = blockStack[blockStack.length - 1];
            if (top.kind === 'if') {
              blockStack.pop();
            } else if (top.kind === 'repeat') {
              if (top.skipping) {
                blockStack.pop();
              } else {
                top.remaining--;
                top.iterations++;
                if (top.remaining > 0 && top.iterations < MAX_ITERATIONS) {
                  idx = top.startIdx;
                } else {
                  if (top.iterations >= MAX_ITERATIONS) {
                    api.showToast('Macro "' + macro.name + '": REPEAT loop exceeded ' + MAX_ITERATIONS + ' iterations');
                  }
                  blockStack.pop();
                }
              }
            } else if (top.kind === 'while') {
              if (top.skipping) {
                blockStack.pop();
              } else {
                top.iterations++;
                if (top.iterations >= MAX_ITERATIONS) {
                  api.showToast('Macro "' + macro.name + '": WHILE loop exceeded ' + MAX_ITERATIONS + ' iterations');
                  blockStack.pop();
                } else {
                  var whileResult = evaluateCondition(top.condition, scope, api);
                  if (whileResult) {
                    idx = top.startIdx;
                  } else {
                    blockStack.pop();
                  }
                }
              }
            }
          }
          continue;
        }

        if (step.type === 'break') {
          if (!isSkipping()) {
            for (var b = blockStack.length - 1; b >= 0; b--) {
              if (blockStack[b].kind === 'repeat' || blockStack[b].kind === 'while') {
                blockStack[b].skipping = true;
                break;
              }
            }
          }
          continue;
        }

        // ---- Executable steps: skip if skipping ----
        if (isSkipping()) continue;

        try {
          if (step.type === 'insert-text') {
            insertText(step.content);
          } else if (step.type === 'insert-date') {
            insertText(formatDate(step.format, new Date()));
          } else if (step.type === 'cardmirror') {
            executeCommand(step.label);
          } else if (step.type === 'set') {
            var exprValue = evaluateExpression(step.expression, scope, api);
            scope[step.variable] = exprValue;
          } else if (step.type === 'insert-var') {
            var varValue = scope.hasOwnProperty(step.variable) ? scope[step.variable] : '';
            insertText(String(varValue));
          } else if (step.type === 'insert-clipboard') {
            navigator.clipboard.readText().then(function (text) {
              insertText(text);
              if (idx < steps.length) {
                setTimeout(runNext, 10);
              }
            }).catch(function (err) {
              api.showToast('Macro "' + macro.name + '": clipboard read failed');
            });
            return;
          } else if (step.type === 'insert-prompt') {
            var response = window.prompt(step.message || 'Enter value:');
            if (response === null) {
              api.showToast('Macro "' + macro.name + '" cancelled.');
              return;
            }
            insertText(response);
          } else if (step.type === 'insert-counter') {
            var storageKey = 'counter_' + step.name;
            var stored = api.storage.get(storageKey);
            var count = (parseInt(stored, 10) || 0) + 1;
            insertText(String(count));
            api.storage.set(storageKey, String(count));
          }
        } catch (err) {
          api.showToast('Macro "' + macro.name + '" failed: ' + err.message);
          return;
        }

        if (idx < steps.length) {
          setTimeout(runNext, 10);
          return;
        }
      }
    }

    runNext();
  }

  // ---- Command ID sanitization ----

  function sanitizeId(name) {
    return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'unnamed';
  }

  // ---- User macro loading (file:// fetch from APPDATA) ----

  function detectMacrosUrl() {
    var href = window.location.href || '';
    var m;
    m = href.match(/file:\/\/\/([A-Z]:\/Users\/[^/]+)\//i);
    if (m) return 'file:///' + m[1] + '/AppData/Roaming/custom-macros/macros/user-macros.json';
    m = href.match(/file:\/\/\/(\/Users\/[^/]+)\//);
    if (m) return 'file:///' + m[1] + '/Library/Application%20Support/custom-macros/macros/user-macros.json';
    m = href.match(/file:\/\/\/(\/home\/[^/]+)\//);
    if (m) return 'file:///' + m[1] + '/.local/share/custom-macros/macros/user-macros.json';
    return null;
  }

  function loadUserMacros() {
    var url = detectMacrosUrl();
    if (!url) return [];
    try {
      var xhr = new XMLHttpRequest();
      xhr.open('GET', url, false);
      xhr.send();
      if (xhr.responseText) return JSON.parse(xhr.responseText);
    } catch (e) {}
    return [];
  }

  // ---- Registration ----

  var macroRegistry = {};

  var allMacros = MACROS.slice();
  var userMacros = loadUserMacros();
  for (var u = 0; u < userMacros.length; u++) {
    var found = false;
    for (var e = 0; e < allMacros.length; e++) {
      if (allMacros[e].name === userMacros[u].name) {
        allMacros[e] = userMacros[u];
        found = true;
        break;
      }
    }
    if (!found) allMacros.push(userMacros[u]);
  }

  for (var r = 0; r < allMacros.length; r++) {
    macroRegistry[allMacros[r].name] = allMacros[r];
  }

  var seenIds = {};
  var commands = [];

  for (var i = 0; i < allMacros.length; i++) {
    var macro = allMacros[i];
    var baseId = 'custom-macros.run-' + sanitizeId(macro.name);
    var cmdId = baseId;
    var suffix = 2;
    while (seenIds[cmdId]) {
      cmdId = baseId + '-' + suffix++;
    }
    seenIds[cmdId] = true;

    commands.push({
      id: cmdId,
      label: 'Macro: ' + macro.name,
      keywords: ['macro', macro.name.toLowerCase()],
      defaultKey: null,
      run: (function (name) {
        return function (api) {
          var m = macroRegistry[name];
          if (m) executeMacro(m, api);
          else api.showToast('Macro "' + name + '" not found');
        };
      })(macro.name),
    });
  }

  commands.push({
    id: 'custom-macros.reload',
    label: 'Custom Macros: Reload',
    keywords: ['macro', 'reload', 'refresh'],
    defaultKey: null,
    run: function (api) {
      var reloaded = loadUserMacros();
      var count = 0;
      for (var i = 0; i < reloaded.length; i++) {
        macroRegistry[reloaded[i].name] = reloaded[i];
        count++;
      }
      api.showToast('Reloaded ' + count + ' macro(s). New macros require restart.');
    },
  });

  window.__registerCardMirrorPlugin &&
    window.__registerCardMirrorPlugin({
      id: 'custom-macros',
      name: 'Custom Macros',
      apiVersion: 1,
      settings: [],
      commands: commands,
    });
})();
